# 45장 프로미스

- JS에서 비동기 처리 패턴 중 하나로 콜백 함수를 사용한다.
- 전통적 콜백 패턴은 가독성이 나쁘고 에러 처리가 용이하지 않으며 여러 개의 비동기 처리를 한 번에 처리하는 데도 한계가 있다.
- ES6에서 비동기 처리 패턴 중 프로미스를 도입했다.

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

```javascript
// GET 요청 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
	  // 서버 응답 출력
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
	}
  };
};

// id가 1인 post 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
	"userId": 1,
	...
}
*/
```

1. 위 예제에서 get 함수가 서버의 응답 결과를 반환하는 방법을 살펴보자.
2. 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않아도 기다리지 않고 즉시 종료된다.
3. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
4. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

- setTimeout 함수의 콜백 함수에서 상위 스코프의 변수에 값을 할당해보자.
- setTimeout 함수는 생성된 타이머를 식별할 수 있는 고유한 타이머 id를 반환하므로 콜백 함수에서 값을 반환하는 것은 무의미하다.

```javascript
let g = 0;

// 비동기 함수 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다.
setTimeout(() => { g = 100; }, 0);
console.log(g); // 0
```

- get 함수가 비동기 함수인 이유는 get 함수 내부의 onload 이벤트 핸들러가 비동기로 동작하기 때문이다.

```javascript
// get함수 응답 결과 반환해보기
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
	  // (1) 서버 응답을 반환한다.
      return JSON.parse(xhr.response);
    } 
      console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

// (2) id가 1인 post를 취득
const response = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response); // undefined
```

1. get 함수 호출 후 HTTP 요청한다. 
2. xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료한다.
3. get 함수에 명시적인 반환문이 없어 undefined를 반환한다(2).
4. xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문(1)은 get 함수의 반환문이 아니다.
5. get 함수는 반환문이 생략되어 암묵적으로 undefined을 반환한다.
6. onload 이벤트 핸들러는 get 함수가 호출하지 않아 반환값을 캐치할 수 없다.

```javascript
document.querySelector('input').oninput = function () {
  console.log(this.value);
  // 이벤트 핸들러에서의 반환은 의미가 없다.
  return this.value;
}
```

(1)에서 서버의 응답을 상위 스코프 변수에 할당해보자

```javascript
let todos;

// get함수 응답 결과 반환해보기
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
	  // (1) 서버 응답을 반환한다.
      todos = JSON.parse(xhr.response);
    } 
      console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
console.log(todos); // undefined
```

1. get 함수는 내부의 onload 이벤트 핸들러가 비동기로 동작하므로 비동기 함수이다.
2. xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러 반환문은 get 함수의 반환문이 아니므로 undefined를 반환한다.
3. get함수의 실행 컨텍스트가 콜 스택에 푸시되고 함수 코드 실행에서 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.
4. get 함수 종료 후 get 함수 실행 컨텍스트는 콜 스택에서 팝되고 console.log가 호출되어 푸시되고 팝된다.
5. console.log 호출 직전에 load 이벤트가 발생하여도 xhr.onload 이벤트 핸들러 프로퍼티에 바인딩된 이벤트 핸들러는 먼저 실행되지 않는다.
6. 서버 응답 도착 후 load 이벤트가 발생할 때 태스크 큐에 저장되어 대기하다가 콜 스택이 비어있게 되면 이벤트 루프에 의해 콜 스택으로 푸시되고 실행된다.
7. 비동기 함수는 비동기 처리 결과를 외부 및 상위 스코프의 변수에 할당할 수도 없다.
8. 따라서 비동기 함수의 처리는 비동기 함수 내부에서 수행되어야 하며 콜백 함수를 전달하는 것이 일반적이다.

```javascript
const get = (url, sucessCallback, failureCallback) => {
const xhr = new XMLHttpRequest();

  //...
	
  xhr.onload = () => {
    if (xhr.status === 200) {
      sucessCallback(//서버 응답 정상 시);
    } else {
      failureCallback(//서버 응답 실패 시 에러 처리)
    }
  }
}

// ...
```

- 비동기 함수의 비동기 처리 결과를 또 비동기 함수로 호출해야 하는 경우를 `콜백 헬`이라고 한다.

```javascript
// 콜백 헬의 전형적인 사례
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d);
      });
    });
  });
});
```
### 45.1.2 에러 처리의 한계

```javascript
// setTimeout 함수실행 후 1초 후 콜백 함수는 에러를 발생시키지만 
// catch 코드 블록에서 캐치되지 않는다.
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러 캐치 불가
  console.error('캐치한 에러', e);
}
```

1. setTimeout 비동기 함수는 콜백 함수 호출을 대기하지 않고 즉시 종료되어 콜 스택에서 푸쉬 후 제거된다.
2. 콜백 함수 실행 시점에서 setTimeout 함수는 콜 스택에서 제거된 상태이다.
3. setTimeout 함수의 콜백 함수의 호출자가 setTimeout 함수라면,
콜 스택의 현재 실행 중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때 현재 실행 중 실행 컨텍스트 하위 실행 컨텍스트가 setTimeout 함수이여야 한다.
4. 에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전 푸시된 실행 컨텍스트 방향)으로 전파된다.
5. 그러나 예제에서처럼 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout함수가 아니므로 catch 블록에서 캐치되지 않는다.

## 45.2 프로미스의 생성

```javascript
// new 연산자와 Promise 키워드로 Promise 객체 생성
// 콜백 함수로 resolve, reject를 인수로 전달받는다.
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리 수행
  if (/* 비동기 처리 성공*/) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
})
```

프로미스의 비동기 처리 상태 정보
- pending: 비동기 처리 수행 전 상태로 프로미스가 생성된 직후 기본 상태
- fulfilled: 비동기 처리가 수행된 상태(성공)로 resolve 함수 호출
- rejected: 비동기 처리가 수행된 상태(실패)로 reject 함수 호출
- 프로미스의 상태는 resolve, reject 함수를 호출하는 것으로 결정된다.
- settled은 pending상태에서 fulfilled 또는 rejected 상태로 변화된 상태이며 settled 상태가 되면 다른 상태로 변화할 수 없다.

## 45.3 프로미스의 후속 처리 메서드

- 프로미스의 처리 결과를 가지고 결과(에러) 처리가 가능하다.
- 후속 메서드는 then, catch, finally가 있다.
- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.

### 45.3.1 Promise.prototype.then

- 두 개의 콜백 함수를 인수로 받는다.
- 첫 번째 콜백 함수는 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
- 두 번째 콜백 함수는 프로미스가 rejected 상태(rejected 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.

```javascript
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled
  
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

- then 메서드는 언제나 프로미스를 반환한다.
- then 메서드의 콜백 함수가 프로미스를 반환하면 프로미스를 반환하지만 반대의 경우 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다.

### 45.3.2 Promise.prototype.catch

- 한 개의 콜백 함수를 인수로 전달받는다.
- catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

```javascript
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected

// catch 메서드는 then(undefined, onRejected)과 동일하게 동작하므로 then 메서드와 마찬가지로 프로미스를 반환한다.
// .then(undefined, e = console.log(e)); // Error: rejected
```

### 45.3.3 Promise.prototype.finally

- 한 개의 콜백 함수를 인수로 전달받는다.
- 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
- 언제나 프로미스를 반환한다.

```javascript
new Promise(() => {})
  .finally(() => console.log('finally')); // finally
```

## 45.4 프로미스의 에러 처리

```javascript
const wrongUrl = '대충잘못된URL';

// 잘못된 URL이 지정되어 에러가 발생
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)) // Error: 404
  // catch 메서드는 내부적으로 then(undefined, onRejected)를 호출하므로
  // then(undefined, err => console.error(err)); 와 같다
```

- then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하며 가독성이 좋지 않다.
- catch 메서드를 모든 then 메서드 호출 이후에 호출하면 비동기 처리에서 발생한 에러와 then 메서드 내부의 에러까지 모두 캐치할 수 있다.

```javascript
promiseGet('대충잘못된URL')
  .then(res => console.xxx(res))
  .catch(err => console.error(err)); // TypeError: console.xxx is not a function
```

## 45.5 프로미스 체이닝

- 프로미스를 연속적으로 호출하는 것

| 후속 처리 메서드 | 콜백 함수의 인수 | 후속 처리 메서드의 반환값 |
|------|---|---|
| then | promiseGet 함수가 반환한 프로미스가 resolve한 값 <br> (id가 1인 psot) | 콜백 함수가 반환한 프로미스 | 
| then | 첫 번째 then 메서드가 반환한 프로미스가 resolve한 값 <br> (post의 userId로 취득한 user 정보) | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| catch <br> ※ 에러가 발생하지 않으면 호출되지 않는다. | promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값 | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 | 

- then, catch, finally 후속 처리 메서드는 콜백 함수가 반환한 프로미스를 반환한다.
- 만약 프로미스가 아닌 값을 반환하여도 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.
- 콜백 패턴은 가독성이 좋지 않아 async/await를 사용해 후속 처리 메서드 없이 동기 처럼 구현할 수 있다.

```javascript
const url = 'url주소';

(async() => {
  // id 가 1인 post의 postId
  const { userId } = await promiseGet(`${url}/posts/1`);
  
  // userId로 user정보 취득
  const userInfo = await promiseGet(`${url}/users/${userId}`);
  
  console.log(userInfo);
})();
```

- async/await도 프로미스를 기반을 동작한다.

## 45.6 프로미스의 정적 메서드

- Promise는 5가지 정적 메서드를 제공한다.

### 45.6.1 Pormise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용

```javascript
// 배열을 resolved하는 프로미스 생성
const resolvedPromise = new Promise(resolve => resolve([1, 2, 3]));
// = Promise.resolve([1, 2, ,3]);
resolvedPromise.then(console.log); // [1, 2, 3]
```

```javascript
// 에러 객체를 reject하는 프로미스 생성
const rejectedPromise = new Pormise((_, reject) => reject(new Error('Error!')));
// = Promise.reject(new Error('Error!'));
rejectedPromise.catch(cosnole.log); // Error: Error!
```

### 45.6.2 Promise.all

- 여러 개의 비동기 처리를 병령 처리할 때 사용

```javascript
const requestData1 = () => 
  new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => 
  new Promise(resolve => setTimeout(() => resolve(2), 3000));
const requestData3 = () => 
  new Promise(resolve => setTimeout(() => resolve(3), 3000));
  
// 세 개의 비동기 처리를 병렬 처리
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3] 약 3초 소요
  .catch(console.error)
```
- Promise.all 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다.
- 모든 프로미스가 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새 프로미스를 반환한다.
- 예제의 경우
	- 첫 번째 프로미스는 3초 후에 1을 resolve한다.
	- 두 번째 프로미스는 2초 후에 2을 resolve한다.
	- 세 번째 프로미스는 1초 후에 3을 resolve한다.
- Promise.all 메서드는 인수로 전달받은 배열의 모든 프로미스가 fulfilled 상태가 되면 종료한다.
- 그 후 resolve된 처리 결과를 모두 배열에 저장하여 새 프로미스를 반환한다. (처리 순서 보장)

- 인수 중 프로미스가 하나라도 rejected 상태가 되면 즉시 종료된다.

```javascript
// 세 번째 프로미스가 제일 먼저 rejected 상태가 된다.
Promise.all([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 3000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 3000)),
])
  .then(console.log)
  .catch(console.log); // Error: Error 3
```

- 인수 중 이터러블 요소가 프로미스가 아니면 Promise.resolve 메서드를 통해 프로미스로 래핑된다.
```javascript
Promise.all([
  1,
  2,
  3,
])
  .then(console.log) // [1, 2, 3]
  .catch(console.log)
```

### 45.6.3 Promise.race

- Promis.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 받는다.
- 가장 먼저 fulfilled 사태가 된 프로미스의 처리 결과를 resolve하는 새 프로미스 반환.
- 인수 중 프로미스가 rejected 상태가 되면 에러를 reject하는 새 프로미스를 즉시 반환한다.

```javascript
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 3000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 3000)) // 3
])
  then(console.log) // 3
  .catch(console.log); 
```

### 45.6.4 Promise.allSettled

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 받는다.
- 인수의 프로미스가 모두 settled(비동기 처리가 수행된 상태)가 되면 처리 결과를 배열로 반환

```javascript
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log);
/*
[
  // 프로미스가 fulfilled인 경우
  {status: "fulfilled", value: 1},
  // 프로미스가 rejected인 경우
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

## 45.7 마이크로태스크 큐

```javascript
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

1. 위 예제는 2 -> 3 -> 1 순으로 출력된다.
2. 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아닌 마이크로태스크 큐에 저장되기 때문이다.
- 마이크로태스크 큐에는 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다.
- 태스크 큐에는 비동기 함수의 콜백 함수는 이벤트 핸들러가 일시 저장된다.
- 마이크로태스크 큐가 태스크 큐보다 우선 순위가 높다.

## 45.8 fetch

- XMLHttpRequest 객체처럼 HTTP 요청 전송 기능을 제공하는 클라이너트 사이드 Web API다.
- 프로미스를 지원한다.

```javascript
// URL, HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달
const promise = fetch(url [, options])
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.

```javascript
// https://jsonplaceholder.typicode.com/todos/1
fetch(URL주소)
  .then(response => console.log(response));
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 프로미스를 반환하므로 후속 처리 메서드로 전달 받을 수 있다.
- Response.prototype 에는 Response 객체에 포함된 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다.
- ex) fetch가 반환한 프로미스가 래핑된 MIME 타입이 application/json인 응답 몸체를 취득할 때 Response.prototype.json 메서드를 사용한다.
- Response.prototype.json 메서드는 Response 객체에서 HTTP 응답 몸체를 취득해 역직력화한다.

```javascript
const wrongUrl = '대충잘못된URL';

// 부적절한 url로 404 Not Found 에러 발생 후 ok가 출력된다.
fetch(wrongUrl)
  .then(() => console.log('ok'))
  .catch(() => console.log('error'));
```

- fetch 함수가 반환하는 프로미스는 404 Not Found, 500 Internal Serve Error 같은 HTTP 에러도 불리언 타입의 ok 상태의 false로 설정된 Response 객체를 resolve한다.
- 오프라인 등 네트워크 장애, CORS 에러 등으로 요청이 완ㄹ되지 않을 때 프로미스를 reject한다.

```javascript
// 404 에러 발생
fetch(wrongUrl)
  // response는 HTTP 응답을 나타내는 Response 객체
  .then(response => {
    if(!response.ok) throw new Error(response.statusText);
	return response.json();
  })
  .then(todo => console.log(todo))
  .catch(err =< console.error(err));
```

- axios는 모든 HTTP 에러를 reject하는 프로미스를 반환한다.

### fetch 함수를 통한 HTTP 요청 전송

```javascript
const request = {
  get(url) {
    return fetch(url);
  },
  post(url, payload) {
    return fetch(url, {
	  method: 'POST',
	  headers: { 'content-Type' : 'application/json'},
	  body: JSON.stringify(payload)
	});
  },
  patch(url, payload) {
    return fetch(url, {
	  method: 'PATCH',
	  headers: {  'content-Type': 'application/json'},
	  body: JSON.stringify(payload)
	});
  },
  delete(url) {
    return fetch(url, {  method: 'DELETE' });
  }
};
```

### 1. GET 요청

```javascript
request.get('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if(!response.ok) throw new Error(response.statusText);
	return response.json();
  })
  .then(todos => console.log(todos))
  .catch(err => console.err(err));
// {userID: 1, id: 1, title: "delectus aut autem", completed: false}
```

### 2. POST 요청

```javascript
request.post('https://jsonplaceholder.typicode.com/todos', {
  userId: 1,
  title: 'JavaScript',
  completed: false
}).then(response =. {
    if(!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todo => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, title: "JavaScript", completed: false, id: 201}
```

### 3. PATCH 요청

```javascript
request.patch('https://jsonplaceholder.typicode.com/todos/1', {
  completed: true
}).then(response =. {
    if(!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todo => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, title: "JavaScript", completed: true}
```

### 4. DELETE 요청

```javascript
request.patch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if(!response.ok) throw new Error(response.statusText);
	.return response.json();
  })
  .then(todo => console.log(todos))
  .catch(err => console.error(err));
//  {}
```
